<?php

namespace App\Model\Entity;

use Cake\ORM\Entity;

class Student extends Entity
{
    protected $_accessible = [
        'first_name' => true,
        'middle_name' => true,
        'last_name' => true,
        'amharic_first_name' => true,
        'amharic_middle_name' => true,
        'amharic_last_name' => true,
        'user_id' => true,
        'accepted_student_id' => true,
        'department_id' => true,
        'high_school' => true,
        'moeadmissionnumber' => true,
        'benefit_group' => true,
        'college_id' => true,
        'original_college_id' => true,
        'gender' => true,
        'ethnicity' => true,
        'nationality' => true,
        'place_of_birth' => true,
        'marital_status' => true,
        'birthdate' => true,
        'language' => true,
        'is_disable' => true,
        'studentnumber' => true,
        'print_count' => true,
        'print_remark' => true,
        'Category' => true,
        'admissionyear' => true,
        'yearLevel' => true,
        'estimated_grad_date' => true,
        'country_id' => true,
        'region_id' => true,
        'zone_id' => true,
        'woreda_id' => true,
        'city_id' => true,
        'address1' => true,
        'program_id' => true,
        'program_type_id' => true,
        'specialization_id' => true,
        'base_program_type_id' => true,
        'zone_subcity' => true,
        'woreda' => true,
        'kebele' => true,
        'house_number' => true,
        'email' => true,
        'email_alternative' => true,
        'phone_home' => true,
        'phone_mobile' => true,
        'pobox' => true,
        'cabinate_address1' => true,
        'cabinate_address2' => true,
        'created' => true,
        'modified' => true,
        'curriculum_id' => true,
        'card_number' => true,
        'ecardnumber' => true,
        'academicyear' => true,
        'graduated' => true,
        'student_national_id' => true,
        'user' => true,
        'accepted_student' => true,
        'department' => true,
        'college' => true,
        'original_college' => true,
        'country' => true,
        'region' => true,
        'zone' => true,
        'city' => true,
        'program' => true,
        'program_type' => true,
        'specialization' => true,
        'base_program_type' => true,
        'curriculum' => true,
        'student_national' => true,
        'alumni' => true,
        'applicable_payments' => true,
        'attendances' => true,
        'certificate_verification_codes' => true,
        'clearances' => true,
        'contacts' => true,
        'cost_shares' => true,
        'cost_sharing_payments' => true,
        'course_adds' => true,
        'course_drops' => true,
        'course_exemptions' => true,
        'course_registrations' => true,
        'course_substitution_requests' => true,
        'curriculum_attachments' => true,
        'department_transfers' => true,
        'disciplines' => true,
        'dismissals' => true,
        'dormitory_assignments' => true,
        'drop_outs' => true,
        'eheece_results' => true,
        'eslce_results' => true,
        'exception_meal_assignments' => true,
        'exit_exams' => true,
        'fx_resit_request' => true,
        'graduate_lists' => true,
        'graduation_works' => true,
        'high_school_education_backgrounds' => true,
        'higher_education_backgrounds' => true,
        'historical_student_course_grade_excludes' => true,
        'historical_student_exam_statuses' => true,
        'makeup_exams' => true,
        'meal_attendances' => true,
        'meal_hall_assignments' => true,
        'medical_histories' => true,
        'otps' => true,
        'payments' => true,
        'placement_entrance_exam_result_entries' => true,
        'placement_participating_students' => true,
        'placement_preferences' => true,
        'program_type_transfers' => true,
        'readmissions' => true,
        'result_entry_assignments' => true,
        'senate_lists' => true,
        'student_evalution_comments' => true,
        'student_evalution_rates' => true,
        'student_exam_statuses' => true,
        'student_name_histories' => true,
        'student_ranks' => true,
        'taken_properties' => true,
        'withdrawals' => true,
        'courses' => true,
        'sections' => true,
    ];
    protected $_virtual = ['full_name']; // Define virtual fields
    protected function _getFullName()
    {
        return $this->first_name . ' ' . $this->middle_name . ' ' . $this->last_name;
    }
}
